### ISSUE TITLE
Errores con las correcciones de palabras

### ISSUE THREAD

**Issue by lautaroMiguez** [OrianaToscano/TP-1-WORDLE#7]
Parece que cuando alguno de los errores se produce, automáticamente corrige las palabras consiguientes con el mismo error, sin importar si es un error de longitud o de que el palabra es inventada 
![Sin título](https://user-images.githubusercontent.com/103506112/166723071-9d5709f9-ccb0-43a7-9259-7f345810af55.png)

**Comment by OrianaToscano** [comment]
Solucionado en el branch *solucion-issue-1*
