### ISSUE TITLE
Problemas de CLS (common language specification

### ISSUE THREAD

**Issue by Sbalanzat914** [OrianaToscano/TP-1-WORDLE#8]
No funciona correctamente con el sistema operativo de Windows
![the-rock](https://user-images.githubusercontent.com/100937259/167886465-fcde131b-0330-4368-b26f-d661df841ca1.gif)

**Comment by OrianaToscano** [comment]
Corregido en la branch [solucion-issue-dos](https://github.com/OrianaToscano/TP-1-WORDLE/tree/solucion-issue-2)
